-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.ticket_app_downtime_tracker
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    internal_ticket character varying(50) COLLATE pg_catalog."default" NOT NULL,
    month_name character varying(20) COLLATE pg_catalog."default",
    service_ticket character varying(50) COLLATE pg_catalog."default",
    ticket_raiser_id integer NOT NULL,
    ticket_raiser character varying(50) COLLATE pg_catalog."default" NOT NULL,
    issue_occurance integer NOT NULL DEFAULT 0,
    ticket_type_id integer NOT NULL,
    ticket_type character varying(50) COLLATE pg_catalog."default",
    shop_id integer NOT NULL,
    shop character varying(50) COLLATE pg_catalog."default",
    ticket_date date NOT NULL,
    ticket_time time without time zone NOT NULL,
    shift_id integer NOT NULL,
    shift character varying(20) COLLATE pg_catalog."default" NOT NULL,
    open_week character varying(255) COLLATE pg_catalog."default" NOT NULL,
    prirority_id integer NOT NULL,
    issue_priority character varying(10) COLLATE pg_catalog."default" NOT NULL,
    donwtime integer,
    short_desc character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description character varying(1000) COLLATE pg_catalog."default" NOT NULL,
    status_id integer NOT NULL,
    issue_status character varying(50) COLLATE pg_catalog."default",
    category_id integer NOT NULL,
    issue_cat character varying(50) COLLATE pg_catalog."default",
    origin_by character varying(50) COLLATE pg_catalog."default",
    origin_team character varying(50) COLLATE pg_catalog."default",
    owner_id integer NOT NULL,
    owner_name character varying(50) COLLATE pg_catalog."default",
    a_category_id integer NOT NULL,
    category character varying(50) COLLATE pg_catalog."default",
    sub_cat character varying(50) COLLATE pg_catalog."default",
    rca character varying(1000) COLLATE pg_catalog."default",
    ica character varying(1000) COLLATE pg_catalog."default",
    pca character varying(1000) COLLATE pg_catalog."default",
    target_date date,
    closed_date date,
    closed_week integer,
    resol_time integer,
    remarks character varying(100) COLLATE pg_catalog."default",
    reviewed_by character varying(50) COLLATE pg_catalog."default",
    reveiw_date date,
    CONSTRAINT ticket_app_downtime_tracker_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ticket_master_app_categroy
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    category character varying(50) COLLATE pg_catalog."default" NOT NULL,
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date timestamp without time zone,
    CONSTRAINT ticket_master_app_categroy_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ticket_master_issue_category
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    category character varying(50) COLLATE pg_catalog."default" NOT NULL,
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date timestamp without time zone,
    CONSTRAINT ticket_master_issue_category_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ticket_master_priority
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    priority character varying(50) COLLATE pg_catalog."default" NOT NULL,
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date timestamp without time zone,
    CONSTRAINT ticket_master_priority_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ticket_master_shift
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    shift_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date timestamp without time zone,
    CONSTRAINT ticket_master_shift_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ticket_master_shops
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    shop_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date timestamp without time zone,
    is_active character varying(10) COLLATE pg_catalog."default" DEFAULT 'ACTIVE'::character varying,
    CONSTRAINT ticket_master_shops_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ticket_master_status
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    status character varying(50) COLLATE pg_catalog."default" NOT NULL,
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date timestamp without time zone,
    CONSTRAINT ticket_master_status_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ticket_master_ticket_type
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    is_active character varying(10) COLLATE pg_catalog."default" NOT NULL DEFAULT 'ACTIVE'::character varying,
    create_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    CONSTRAINT ticket_master_ticket_type_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ticket_master_user
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date timestamp without time zone,
    is_active character varying(10) COLLATE pg_catalog."default" DEFAULT 'ACTIVE'::character varying,
    user_name character varying(50) COLLATE pg_catalog."default",
    user_pwd character varying(255) COLLATE pg_catalog."default",
    email character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT ticket_master_user_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.ticket_app_downtime_tracker
    ADD CONSTRAINT ticket_app_downtime_tracker_a_category_id_fkey FOREIGN KEY (a_category_id)
    REFERENCES public.ticket_master_app_categroy (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ticket_app_downtime_tracker
    ADD CONSTRAINT ticket_app_downtime_tracker_category_id_fkey FOREIGN KEY (category_id)
    REFERENCES public.ticket_master_issue_category (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ticket_app_downtime_tracker
    ADD CONSTRAINT ticket_app_downtime_tracker_owner_id_fkey FOREIGN KEY (owner_id)
    REFERENCES public.ticket_master_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ticket_app_downtime_tracker
    ADD CONSTRAINT ticket_app_downtime_tracker_prirority_id_fkey FOREIGN KEY (prirority_id)
    REFERENCES public.ticket_master_priority (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ticket_app_downtime_tracker
    ADD CONSTRAINT ticket_app_downtime_tracker_shift_id_fkey FOREIGN KEY (shift_id)
    REFERENCES public.ticket_master_shift (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ticket_app_downtime_tracker
    ADD CONSTRAINT ticket_app_downtime_tracker_shop_id_fkey FOREIGN KEY (shop_id)
    REFERENCES public.ticket_master_shops (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ticket_app_downtime_tracker
    ADD CONSTRAINT ticket_app_downtime_tracker_status_id_fkey FOREIGN KEY (status_id)
    REFERENCES public.ticket_master_status (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ticket_app_downtime_tracker
    ADD CONSTRAINT ticket_app_downtime_tracker_ticket_raiser_id_fkey FOREIGN KEY (ticket_raiser_id)
    REFERENCES public.ticket_master_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ticket_app_downtime_tracker
    ADD CONSTRAINT ticket_app_downtime_tracker_ticket_type_id_fkey FOREIGN KEY (ticket_type_id)
    REFERENCES public.ticket_master_ticket_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;
