/*
========================================================================
DDL Script: Create Incident & Downtime Tracker Schema
========================================================================
Script Purpose:
  This script initializes the schema for tracking application downtime
  and support tickets. It establishes core master lookup tables and 
  the main tracking transactional table, enforcing data integrity via 
  Foreign Key constraints.
  
Target DB Platform: PostgreSQL (12+)
Generated / Modified: 2026
========================================================================
*/

-- ---------------------------------------------------------------------
-- Environment Setup & Initialization
-- ---------------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS public;

-- Drop existing tables to ensure a clean, repeatable build.
-- Ordered carefully to prevent dependency/foreign key violations.
DROP TABLE IF EXISTS public.ticket_app_downtime_tracker CASCADE;
DROP TABLE IF EXISTS public.ticket_master_app_categroy CASCADE;
DROP TABLE IF EXISTS public.ticket_master_issue_category CASCADE;
DROP TABLE IF EXISTS public.ticket_master_priority CASCADE;
DROP TABLE IF EXISTS public.ticket_master_shift CASCADE;
DROP TABLE IF EXISTS public.ticket_master_shops CASCADE;
DROP TABLE IF EXISTS public.ticket_master_status CASCADE;
DROP TABLE IF EXISTS public.ticket_master_ticket_type CASCADE;
DROP TABLE IF EXISTS public.ticket_master_user CASCADE;

BEGIN;

-- ---------------------------------------------------------------------
-- 1. Master / Lookup Tables
-- ---------------------------------------------------------------------

-- Reference: Application Category Master
CREATE TABLE public.ticket_master_app_categroy (
    id           INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    category     VARCHAR(50) NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT ticket_master_app_categroy_pkey PRIMARY KEY (id)
);

-- Reference: Root-Cause / Issue Category Master
CREATE TABLE public.ticket_master_issue_category (
    id           INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    category     VARCHAR(50) NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT ticket_master_issue_category_pkey PRIMARY KEY (id)
);

-- Reference: Ticket Priority Hierarchy (e.g., P1, P2, P3)
CREATE TABLE public.ticket_master_priority (
    id           INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    priority     VARCHAR(50) NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT ticket_master_priority_pkey PRIMARY KEY (id)
);

-- Reference: Operational Shift Master
CREATE TABLE public.ticket_master_shift (
    id           INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    shift_name   VARCHAR(50) NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT ticket_master_shift_pkey PRIMARY KEY (id)
);

-- Reference: Manufacturing / Retail Shop Floor Master
CREATE TABLE public.ticket_master_shops (
    id           INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    shop_name    VARCHAR(50) NOT NULL,
    is_active    VARCHAR(10) NOT NULL DEFAULT 'ACTIVE',
    created_date TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT ticket_master_shops_pkey PRIMARY KEY (id)
);

-- Reference: Lifecycle Status Master (e.g., Open, In-Progress, Closed)
CREATE TABLE public.ticket_master_status (
    id           INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    status       VARCHAR(50) NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT ticket_master_status_pkey PRIMARY KEY (id)
);

-- Reference: Ticket Classification Master (e.g., Bug, Request, Incident)
CREATE TABLE public.ticket_master_ticket_type (
    id           INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    name         VARCHAR(50) NOT NULL,
    is_active    VARCHAR(10) NOT NULL DEFAULT 'ACTIVE',
    create_date  TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT ticket_master_ticket_type_pkey PRIMARY KEY (id)
);

-- Reference: System Users, Raisers, and Resolution Owners
CREATE TABLE public.ticket_master_user (
    id           INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    name         VARCHAR(50) NOT NULL,
    user_name    VARCHAR(50),
    user_pwd     VARCHAR(255), -- Securely hashed password text
    email        VARCHAR(50),
    is_active    VARCHAR(10) NOT NULL DEFAULT 'ACTIVE',
    created_date TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT ticket_master_user_pkey PRIMARY KEY (id)
);

-- ---------------------------------------------------------------------
-- 2. Transactional / Core Metrics Table
-- ---------------------------------------------------------------------

-- Central Log: Tracks all app downtime occurrences and ticket lifecycles
CREATE TABLE public.ticket_app_downtime_tracker (
    -- Primary Identifier
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    
    -- Document Reference Keys
    internal_ticket    VARCHAR(50) NOT NULL,
    service_ticket     VARCHAR(50),
    
    -- Date & Time Attributes
    ticket_date        DATE NOT NULL,
    ticket_time        TIME WITHOUT TIME ZONE NOT NULL,
    month_name         VARCHAR(20),
    open_week          VARCHAR(255) NOT NULL,
    target_date        DATE,
    closed_date        DATE,
    closed_week        INTEGER,
    reveiw_date        DATE,
    
    -- Master Foreign Keys & Redundant Descriptive Fields (For Fast Reporting)
    ticket_raiser_id   INT NOT NULL,
    ticket_raiser      VARCHAR(50) NOT NULL,
    
    ticket_type_id     INT NOT NULL,
    ticket_type        VARCHAR(50),
    
    shop_id            INT NOT NULL,
    shop               VARCHAR(50),
    
    shift_id           INT NOT NULL,
    shift              VARCHAR(20) NOT NULL,
    
    prirority_id       INT NOT NULL,
    issue_priority     VARCHAR(10) NOT NULL,
    
    status_id          INT NOT NULL,
    issue_status       VARCHAR(50),
    
    category_id        INT NOT NULL,
    issue_cat          VARCHAR(50),
    
    a_category_id      INT NOT NULL,
    category           VARCHAR(50),
    
    owner_id           INT NOT NULL,
    owner_name         VARCHAR(50),
    
    -- Quantitative / Metric Fields
    issue_occurance    INTEGER NOT NULL DEFAULT 0,
    donwtime           INTEGER, -- System downtime measured in minutes
    resol_time         INTEGER, -- Total resolution duration in minutes
    
    -- Log Descriptions & Actions Taken (RCA / ICA / PCA)
    short_desc         VARCHAR(50) NOT NULL,
    description        VARCHAR(1000) NOT NULL,
    rca                VARCHAR(1000), -- Root Cause Analysis
    ica                VARCHAR(1000), -- Immediate Corrective Action
    pca                VARCHAR(1000), -- Preventive Corrective Action
    
    -- Organizational Auditing Fields
    origin_by          VARCHAR(50),
    origin_team        VARCHAR(50),
    remarks            VARCHAR(100),
    reviewed_by        VARCHAR(50),

    -- Constraints & Referential Integrity Definitions
    CONSTRAINT ticket_app_downtime_tracker_pkey 
        PRIMARY KEY (id),
        
    CONSTRAINT ticket_app_downtime_tracker_a_category_id_fkey 
        FOREIGN KEY (a_category_id) REFERENCES public.ticket_master_app_categroy (id)
        ON UPDATE NO ACTION ON DELETE NO ACTION,
        
    CONSTRAINT ticket_app_downtime_tracker_category_id_fkey 
        FOREIGN KEY (category_id) REFERENCES public.ticket_master_issue_category (id)
        ON UPDATE NO ACTION ON DELETE NO ACTION,
        
    CONSTRAINT ticket_app_downtime_tracker_owner_id_fkey 
        FOREIGN KEY (owner_id) REFERENCES public.ticket_master_user (id)
        ON UPDATE NO ACTION ON DELETE NO ACTION,
        
    CONSTRAINT ticket_app_downtime_tracker_prirority_id_fkey 
        FOREIGN KEY (prirority_id) REFERENCES public.ticket_master_priority (id)
        ON UPDATE NO ACTION ON DELETE NO ACTION,
        
    CONSTRAINT ticket_app_downtime_tracker_shift_id_fkey 
        FOREIGN KEY (shift_id) REFERENCES public.ticket_master_shift (id)
        ON UPDATE NO ACTION ON DELETE NO ACTION,
        
    CONSTRAINT ticket_app_downtime_tracker_shop_id_fkey 
        FOREIGN KEY (shop_id) REFERENCES public.ticket_master_shops (id)
        ON UPDATE NO ACTION ON DELETE NO ACTION,
        
    CONSTRAINT ticket_app_downtime_tracker_status_id_fkey 
        FOREIGN KEY (status_id) REFERENCES public.ticket_master_status (id)
        ON UPDATE NO ACTION ON DELETE NO ACTION,
        
    CONSTRAINT ticket_app_downtime_tracker_ticket_raiser_id_fkey 
        FOREIGN KEY (ticket_raiser_id) REFERENCES public.ticket_master_user (id)
        ON UPDATE NO ACTION ON DELETE NO ACTION,
        
    CONSTRAINT ticket_app_downtime_tracker_ticket_type_id_fkey 
        FOREIGN KEY (ticket_type_id) REFERENCES public.ticket_master_ticket_type (id)
        ON UPDATE NO ACTION ON DELETE NO ACTION
);

COMMIT;
